Cost center profit and expense report
IMA-WorldHealth/bhima pull request #6046
Opened 2021-10-20 23:51 UTC by mbayopanda

This PR is related to #6042 

![image](https://user-images.githubusercontent.com/5445251/138187846-5299d398-561d-4e3e-8a11-8fe34f6ad37d.png)

Close #6042

2021-10-20 23:57 UTC, mbayopanda commented
bors try

2021-10-21 08:50 UTC, jniles requested changes
I like this report.  It's a good idea - I didn't understand what the purpose was when you made the issue, but I agree it is useful.

You should change all references to "profit" to either "revenue" or "income".  Both of the latter are correct, but the former is defined as the money made by a service after expenses.

2021-10-21 08:50 UTC, jniles commented on server/controllers/finance/reports/cost_center_step_down/profit_and_expense.js
> +      SELECT cc.label, 0 AS profit, SUM(gl.debit_equiv - gl.credit_equiv) expense, gl.cost_center_id AS ccId
Instead of a UNION, can you use a CASE or an IF statement?  It would make the code both easier to read, and probably faster.

2021-10-21 08:50 UTC, jniles commented on client/src/i18n/en/cost_center.json
> +      "COST_CENTER_PROFIT_AND_EXPENSE" : "Cost center profit and expense",
I think this title is misleading.  This is the report of the direct revenue and costs.  It does not include the total cost of operation that we'd get from the step-down analysis.

Let's instead call this "Direct Revenue & Expenses for a  Cost Center".

"Profit" in English also means $(revenue - expense).

2021-10-21 08:50 UTC, jniles commented on client/src/i18n/en/cost_center.json
> +      "COST_CENTER_PROFIT_AND_EXPENSE_DESCRIPTION" : "This report displays cost centers values according their profit and expense"
I propose:

This report displays the direct revenue and costs associated with each cost center.  To get the total costs and revenue by revenue-generating cost center, please see the step-down analysis report.

2021-10-21 19:19 UTC, mbayopanda commented
@jniles changes landed

2021-10-23 06:01 UTC, jniles reviewed
This is nearly there.  Just one more `profit` reference to change.

2021-10-23 06:01 UTC, jniles commented on server/controllers/finance/reports/cost_center_step_down/income_and_expense.js
> +      GROUP BY cc.id
Much cleaner!

2021-10-23 06:01 UTC, jniles commented on server/controllers/finance/reports/cost_center_step_down/income_and_expense.js
> +    firstCurrency,
Eventually, we'll want to make this into a reusable component.

2021-10-23 06:01 UTC, jniles commented on client/src/i18n/en/tree.json
> +    "COST_CENTER_PROFIT_EXPENSE_REPORT": "Cost centers profit and expense",
Can you update this one as well to be `INCOME_AND_EXPENSE` instead of making reference to profit as explained in the last review?

2021-10-24 07:34 UTC, jniles approved these changes
Changes LGTM.

bors r+

2021-10-24 07:37 UTC, merged